extends: airbnb-base
env:
  browser: true
  node: true
  mocha: true
plugins:
  - import
rules:
  no-console: off
  no-nested-ternary: off
  no-shadow: off
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
  import/no-dynamic-require: off
